# NOTE: To be safe, use spaces, not tabs
# Experimental Design Parameters
num_stimuli: 25 
#for textures 37 for materials
overlap: 2 # do not change unless necessary - controls size of overlapping set of stimuli across two trials
num_stimuli_per_trial: 8
path_to_stimulus_list: './texture-exp-materials/dgea3pt_stimuli.txt'
# Modeling Parameters
sigma: 1
max_trials: 500000
model_dimensions: [1, 2, 3, 4, 5]
epsilon: 1e-30
minimization: 'gradient-descent'
tolerance: 1e-5
fatol: 1e-5
max_iterations: 30000
learning_rate: 0.02
